= QAvalidator Sonar Plugin

Plugin to show the QAvalidator results in SonarQube.

The QAware Quality Contact Plugin in SonarQube accesses the metrics from this QAvalidator SonarQube plugin.

== Development and Testing

To test this plugin, start a local SonarQube, deploy the plugin, and do an analysis.

=== Local SonarQube

There is a SonarQube in the SEU at V:/software/sonarqube-5.6.4

Use the command

  V:\software\sonarqube-5.6.4\bin\windows-x86-64\StartSonar.bat

to start the Sonar server. It comes up on http://localhost:9000

=== Deploy the Plugin

Just copy the plugin jar file to the `plugins` dir:

  $ gradlew clean build
  $ cp build/libs/qav-sonar-plugin-<VERSION>.jar /v/software/sonarqube-5.6.4/extensions/plugins/

or

  $ gradlew clean build localDeploy

=== Do a Test Analysis

Use QAvalidator itself for analysis:

  $ export SONAR_HOST_URL=http://localhost:9000
  $ gradlew clean build sonarqube --console plain

To see `info` or `debug` output from the plugin, do

  $ gradlew clean build sonarqube --console plain --info/--debug

TIP: If there is an error like `"Unable to open Git repository"`
then temporarily move away the file `v:/home/.gitconfig`.


== Open Issues

* It would be nice if there can be infos in the list (is that "issues"?) _-> This is more complicated: requires definition of a "rule" and a whole bunch of boilerplate code._
