= QAvalidator Documentation Generator

This project contains:

* Documentation annotations for QAvalidator
* An annotation processor which generates AsciiDoc documentation from these annotations.

This is used to explain the QAvalidator Analysis DSL.

* Only creates the output directory when the first output is written.
  Avoids creating output directoris when no output is generated at all, e.g. in the Maven Plugin.

* To set the output path, set the apt-option `genDocDir`, i.e. do something like this in the build.gradle:

[source: groovy]
-----
compileGroovy {
    groovyOptions.javaAnnotationProcessing = true
    aptOptions.processorArgs = [
        genDocDir: project(':qav-doc').projectDir.absolutePath + "/src-gen/generated-docs"]
}
-----

== Open Issues / Improvements

* The Groovy Compiler has a bug: It does not offer the JavaDoc comments to the annotation processor.
  That's the reason why we have descriptions of the commands and their parameters in annotations instead of using JavaDoc.
